name: Build and deploy Python project to Azure Function App - prxh-news-scraper 

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './package' # Deployment directory
  PYTHON_VERSION: '3.11' # Python version

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies inside function folder
        run: |
          pip install --upgrade pip
          pip install --target=ScrapeMedicalNews/.python_packages -r requirements.txt

      - name: Create deployment package
        run: |
          mkdir -p package
          cp -r ScrapeMedicalNews host.json requirements.txt package/
          tar -czf release.tar.gz package  # Creates a single deployable archive
        shell: bash

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unpack artifact for deployment
        run: tar -xzf release.tar.gz -C .

      - name: Ensure Azure installs dependencies (just in case)
        run: |
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" > .env
          echo "ENABLE_ORYX_BUILD=True" >> .env

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'prxh-news-scraper'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          enable-oryx-build: true
