name: Build and deploy Python project to Azure Function App - prxh-news-scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Set this to root
  PYTHON_VERSION: '3.11' # Python version

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies locally (optional)
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Create deployment package
        run: |
          mkdir -p package
          rsync -av --exclude=.git/ --exclude=.github/ --exclude=release.zip ./ package/
          cd package
          zip -r ../release.zip ./*
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .    

      - name: Ensure Azure installs dependencies
        run: |
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" > .env
          echo "ENABLE_ORYX_BUILD=True" >> .env

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DCD45E5C4CD42E3B0F7EBEA619A2197 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_41E6A73B9D5F4ED4A7C82A774117AD25 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B8DEF63586A94CA1BEAEBD73C06B39AF }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'prxh-news-scraper'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          enable-oryx-build: true # Forces Azure to install dependencies correctly
